### ISSUE TITLE
Expose ts source code

### ISSUE THREAD

**Issue by princemaple** [Jon-Millent/nomoney#4]
Hi,

Could you include src in the package so ts users can use that directly?

Thanks.

**Comment by Jon-Millent** [comment]
Thank you for your suggestion, I will add Ts support this week 😁

**Comment by princemaple** [comment]
Appreciate the quick response! ❤️ love this simple little package.

**Comment by Jon-Millent** [comment]
After reading your question, I tested it today, I think I have added support for typescript types before.
Or did I understand what you mean wrong? 😂


![image](https://user-images.githubusercontent.com/17584565/127628583-3b97110f-021d-430e-a7bd-55e4dc7a0b70.png)

**Comment by princemaple** [comment]
The types are good. I was merely asking for including the src folder into the final package. So you don't have to include the separate types, and users can import from proper modules. Currently the packaging is in either common js or amd packaging format, which is not ideal.

**Comment by princemaple** [comment]
It's more about packaging really :)
