### ISSUE TITLE
Behavior question

### ISSUE THREAD

**Issue by princemaple** [Jon-Millent/nomoney#9]
Hello,

Is this expected behavior? I thought it would round up.

`nomoney.stringify('10051.9953')` -> `"拾壹万零伍拾壹元玖角玖分"`

Thanks!

**Comment by Jon-Millent** [comment]
Hello, among China’s currency units, “分” is the smallest currency unit.
<img width="656" alt="image" src="https://github.com/Jon-Millent/nomoney/assets/17584565/cb5e10b7-1adb-46ed-95b5-4d44e5c41909">

**Comment by princemaple** [comment]
Ah so anything behind is discarded?

**Comment by Jon-Millent** [comment]
Yes, 🤣 I dropped the word after "分" in the code. 😀 I would like to know what you think is the expectation of `nomoney.stringify('10051.9953')`?  😁

**Comment by princemaple** [comment]
Thought it'd be 10052 but well :)

It's okay. Some bad code leaked extra decimal points. It should always be rounded by code first then sent to nomoney for formatting.

**Comment by Jon-Millent** [comment]
Yes, I agree with you :)
